name: eohe
channels:
  - rdkit
  - anaconda
  - pytorch
  - codecarbon
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _pytorch_select=0.1=cpu_0
  - apscheduler=3.8.0
  - backcall=0.2.0
  - beautifulsoup4=4.10.0
  - blas=1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - cairo=1.16.0
  - cairocffi=1.2.0
  - cairosvg=2.7.0
  - certifi=2021.5.30
  - cffi=1.14.0
  - chardet=4.0.0
  - charset-normalizer=2.0.4
  - click=8.0.3
  - codecarbon=1.2.0
  - colorama=0.4.4
  - conda=4.9.2
  - conda-build=3.20.5
  - conda-package-handling=1.7.2
  - cpuonly=2.0=0
  - cryptography=3.3.1
  - cssselect2=0.2.1
  - cudatoolkit=11.3.1
  - cudnn=8.2.1=cuda11.3_0
  - cycler=0.11.0
  - dash=2.10.2
  - dash-bootstrap-components=1.5.0
  - dataclasses=0.8
  - dbus=1.13.18
  - decorator=5.1.1
  - deepsmiles=1.0.1
  - defusedxml=0.7.1
  - entrypoints=0.3
  - expat=2.4.9
  - filelock=3.0.12
  - fire=0.1.3
  - flask=1.1.2
  - fontconfig=2.14.1
  - freetype=2.12.1
  - glib=2.69.1
  - glob2=0.7
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=3.3
  - intel-openmp=2022.1.0
  - ipykernel=5.3.4
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - itsdangerous=2.0.1
  - jedi=0.17.0
  - jinja2=2.11.2
  - joblib=1.3.0
  - jpeg=9e
  - jupyter_client=7.1.2
  - jupyter_core=4.8.1
  - kiwisolver=1.3.1
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - libarchive=3.4.2
  - libblas=3.9.0
  - libboost=1.73.0
  - libcblas=3.9.0
  - libedit=3.1.20221030
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - liblapack=3.9.0
  - liblief=0.10.1
  - libpng=1.6.37
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtiff=4.1.0
  - libuuid=1.41.5
  - libuv=1.40.0
  - libxcb=1.15
  - libxml2=2.9.14
  - lz4-c=1.9.4
  - markupsafe=2.0.1
  - matplotlib=3.3.4
  - matplotlib-base=3.3.4
  - matplotlib-inline=0.1.2
  - matplotlib-label-lines=0.4.2
  - matplotlib-scalebar=0.7.2
  - matplotlib-venn=0.11.7
  - matplotlib2tikz=0.7.5
  - matplotlibhelper=0.0.10
  - mkl=2020.2=256
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - ncurses=6.3
  - nest-asyncio=1.5.1
  - ninja=1.10.2
  - ninja-base=1.10.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1s
  - packaging=21.3
  - pandas=1.1.3
  - panflute=2.1.3
  - parso=0.8.3
  - patchelf=0.15.0
  - patsy=0.5.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=21.2.2
  - pixman=0.40.0
  - pkginfo=1.8.2
  - plotly=5.17.0
  - prompt-toolkit=3.0.20
  - psutil=5.7.2
  - ptyprocess=0.7.0
  - py-boost=1.73.0
  - py-cpuinfo=8.0.0
  - py-lief=0.10.1
  - pycosat=0.6.3
  - pycparser=2.21
  - pygments=2.11.2
  - pynvml=11.5.0
  - pyopenssl=20.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pysocks=1.7.1
  - python=3.6.13
  - python-dateutil=2.8.2
  - python-libarchive-c=2.9
  - python_abi=3.6
  - pytorch=1.3.1=cpu_py36h62f834f_0
  - pytorch-model-summary=0.1.1
  - pytorch-mutex=1.0=cpu
  - pytz=2021.3
  - pyyaml=5.3.1
  - pyzmq=22.2.1
  - qt=5.9.7
  - rdkit=2020.09.1.0
  - readline=8.2
  - requests=2.27.1
  - ripgrep=13.0.0
  - roman=3.3
  - ruamel_yaml=0.15.100
  - scikit-learn=0.24.2
  - seaborn=0.10.1
  - selfies=1.0.2
  - setuptools=58.0.4
  - sip=4.19.8
  - six=1.16.0
  - soupsieve=2.3.1
  - sqlite=3.40.1
  - statsmodels=0.9.0
  - sugartex=0.1.16
  - tenacity=8.2.2
  - threadpoolctl=2.2.0
  - tinycss2=1.2.1
  - tk=8.6.12
  - tornado=6.1
  - tqdm=4.63.0
  - traitlets=4.3.3
  - typing_extensions=4.1.1
  - tzlocal=2.0.0
  - urllib3=1.26.8
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=2.0.2
  - wheel=0.37.1
  - xz=5.2.10
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.4.9
  - pip:
      - fcd-torch==1.0.7
      - numpy==1.19.5
      - scipy==1.5.4
      - torch==1.10.2
